config/routes.rb
Donate::Application.routes.draw do
  devise_for :hospitals
  resources :hospitals
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/help', to: 'static_pages#help', via: 'get'
  match '/about', to: 'static_pages#about', via: 'get'
  root  'static_pages#home'
  devise_for :users
  resources :users

end

app/models/hospital.rb
class Hospital < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

   attr_accessible :email, :password, :address, :phone, :bloodgroup, :name, :zip, :availability, :lastdonated, :age, :city, :gender

   def self.search(search, group)
   	if search
   		find(:all, :conditions => ['zip LIKE ? AND bloodgroup LIKE ?', "%#{search}%", "%#{group}%"])

   	else
   		find(:all)
   	end
   end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  #http_basic_authenticate_with :name => "Devang", :password => "b12059"
  include SessionsHelper
  require 'will_paginate/array'

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << [:name, :address, :bloodgroup, :phone, :zip, :availability, :lastdonated, :age, :city, :gender ]
    devise_parameter_sanitizer.for(:account_update) << [:name, :address, :bloodgroup, :phone, :zip, :availability, :lastdonated, :age, :city, :gender]
  end
end

app/controllers/hospitals_controller.rb
class HospitalsController < ApplicationController
  def new
  end

  def edit
  end

  def index
  	@hospitals = Hospital.paginate(page: params[:page])
  end

  def show
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def contact
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  	@user = User.find(params[:id])
  end

  def index
  	@users = User.search(params[:search], params[:group]).paginate(page: params[:page])

    respond_to do |format|
        format.html # index.html.erb
        format.json { render json: @users }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

		# Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "Donate"
    if page_title.empty?
      base_title
    else
      "#{page_title} | #{base_title}"
    end
  end

end

app/helpers/hospitals_helper.rb
module HospitalsHelper
	# Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for_hospital(hospital, options = { size: 50 })
    gravatar_id = Digest::MD5::hexdigest(hospital.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: hospital.name, class: "gravatar")
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper

	def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.url if request.get?
  end

  def store_previous_location
    session[:return_to] = URI(request.referer).path
  end

  def signed_in_user
      unless signed_in?
        store_location
        redirect_to signin_url, notice: "Please sign in."
      end
  end


  def current_user?(user)
    user == current_user
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
	# Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for_user(user, options = { size: 50 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/hospitals/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>
      
      <%= form_tag users_path, :method => 'get' do %>
      <p>
        <%= text_field_tag :search, params[:bloodsearch] %><br/>
        <%= text_field_tag :group, params[:group] %>
        <%= submit_tag "Search" %><br/>
      </p>
      <% end %>

<%= will_paginate %>

<ul class="users">
  <% @hospitals.each do |hospital| %>
    <li>
      <%= gravatar_for_hospital hospital, size: 52 %>
      <%= link_to hospital.hospital_name, hospital %>
      <% if current_hospital.admin? && !current_hospital?(user) %>
    | <%= link_to "delete", user, method: :delete,
                                  data: { confirm: "You sure?" } %>
                                  <% end %>
      
    </li>
  <% end %>
</ul>

<%= will_paginate %>

app/views/hospitals/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/hospitals/show.html.erb
<h1>Hospitals#show</h1>
<p>Find me in app/views/hospitals/show.html.erb</p>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <%= link_to "Donate",   root_path %>
    by <a href="https://www.facebook.com/devangtgr8">Devang Gupta</a>
      ,<a href="https://www.facebook.com/shivamsatija04">Abhimanyu Mittal </a>
      <a href="https://www.facebook.com/shivamsatija04">Sagar Ghai </a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "Help", help_path %></li>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="#">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Donate", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <% if signed_in? %>
          <li><%= link_to "Home", current_user %></li>
          <%end%>
          <% if signed_in? %>
            <li><%= link_to "Users", users_path %></li>
            <li><%= link_to "Hospitals", hospitals_path %>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", edit_user_registration_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", destroy_user_session_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
          <li><%= link_to "Users", users_path %></li>
          <li><%= link_to "Hospitals", hospitals_path %>
            <li><%= link_to "Sign in", new_user_session_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim'%>

</head>
<body>
	<div>
		<% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "alert alert-#{key}") %>
      	<% end %>
		<%= render 'layouts/header' %>
	
		<div class="container">

			<%= yield %>

		</div>

		<%= render 'layouts/footer' %>

		<%= debug(params) if Rails.env.development? %>
</div>
</body>
</html>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for_user(current_user, size: 52), current_user %>
<h1>
  <%= link_to current_user.name, current_user %>
</h1>

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
  </head>
  <body>
    <h1>About Us</h1>
    <p>
      
    </p>
  </body>
</html>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact Us') %>
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
  </head>
  <body>
    <h1>Contact Us</h1>
    <p>
      
    </p>
  </body>
</html>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
  </head>
  <body>
    <h1>Help</h1>
    <p>
      
    </p>
  </body>
</html>

app/views/static_pages/home.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
  </head>
  <body>



  <% if signed_in? %>
  <div class="row">
    <aside class="span4">
      <section>
        <%= render 'shared/user_info' %>
        
      </section>
      <section>
        
      </section>
      <section>
       
      </section>
    
      
    </aside>
     
     
  </div>

  <%else %>

  	<div class="center hero-unit">
    	<h1>Donate</h1>
    	<h2>Donated blood and organs database</h2>
       
      <% if user_signed_in? %>
        Signed in as <%= current_user.email %>. Not you?
      <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
      <% else %>
      <%= link_to "Sign up now!", new_user_registration_path, class: "btn btn-large btn-primary" %>
      <% end %>
      
  
    	
    </div>

    <%end%>
  </body>
</html>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>
      
      <%= form_tag users_path, :method => 'get' do %>
      <p>
        <%= text_field_tag :search, params[:bloodsearch] %><br/>
        <%= text_field_tag :group, params[:group] %>
        <%= submit_tag "Search" %><br/>
      </p>
      <% end %>

<%= will_paginate %>

<ul class="users">
  <% @users.each do |user| %>
    <li>
      <%= gravatar_for_user user, size: 52 %>
      <%= link_to user.name, user %>
      <% if signed_in? %>
        
     
      <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "delete", user, method: :delete,
                                  data: { confirm: "You sure?" } %>
                                  <% end %>

      <% end %>
      <br>
      <b>Blood Group : <%= user.bloodgroup %></b>
      <br>
      <b>Postal Code : <%= user.zip %></b>
      
    </li>
  <% end %>
</ul>

<%= will_paginate %>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<aside>
<div class="row">
  <aside class="span4">
    <section>
      <h1>
        <%= gravatar_for_user @user %>
        <%= link_to @user.name, @user%>
        <% if current_user.admin? && !current_user?(@user) %>
        | <%= link_to "delete", @user, method: :delete,
                                  data: { confirm: "You sure?" } %>
                                  <% end %>
      </h1>  
    </section>
    <section>
      <b>Age        :</b> <%= @user.age %> <br>
      <b>Gender     :</b> <%= @user.gender %> <br>
      <b>Bloodgroup :</b> <%= @user.bloodgroup %> <br>
      <b>Mobile     :</b> <%= @user.phone %> <br>
      <b>Address    :</b> <%= @user.address %> <br>
      <b>City       :</b> <%= @user.city %> <br>
    </section>
  </div>
  </aside>
  <section>
  <div class="span8">
  	
  </div>
</section>
</div>